version: '3.8'

services:
  pdf-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-chat-app
    ports:
      - "8501:8501"
    volumes:
      - ./refdocs:/app/refdocs
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - pdf-chat-network

networks:
  pdf-chat-network:
    driver: bridge

volumes:
  chroma_db_data:
    driver: local
